language: android

android:
  components:
      - platform-tools
      - tools
      - build-tools-25.0.1
      - android-25
      - extra-android-m2repository
jdk:
  - oraclejdk8
script:
   - ./gradlew build connectedCheck